# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworkManagerApp', '0004_auto_20170524_1718'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='box',
            unique_together=set([]),
        ),
    ]
